## Important Lists

### Database Columns (When Modifying)

- Always include ALL existing column attributes in migration modifications
- Dropped columns = lost data
- Use `$table->timestamp('created_at')->useCurrent()` not just `$table->timestamp('created_at')`

### Model Conventions

- Table name: snake_case, plural (users, blog_posts)
- Primary key: `protected $primaryKey = 'uuid'` or `id`
- Timestamps: `public $timestamps = true`
- Casts: Define in `casts()` method, not `$casts` property
- Fillable: Use `$fillable` for mass assignment
- Relationships: camelCase methods (hasMany, belongsTo)

### ULID Conventions

This project uses ULIDs instead of auto-incrementing IDs for better distributed systems support.

#### Model
```php
use App\Concerns\HasUlids;

class Chat extends Model
{
    use HasUlids;
    // ULID is auto-generated by the trait
}
```

#### Migration
```php
// For main table
$table->ulid('id')->primary();
$table->foreignUlid('user_id')->index();

// For related tables (always use foreignUlid for foreign keys)
$table->foreignUlid('conversation_id')->index();
$table->foreignUlid('user_id')->index();
```

#### Key Points
- Use `HasUlids` trait in models (auto-generates ULID on create)
- Use `foreignUlid()` for foreign keys in migrations (not `foreignId`)
- ULIDs are sortable by time and are 26 characters long
- Route binding automatically handles ULID conversion

### Route Naming

- Use `Route::name('users.')->group(...)` for namespacing
- Frontend: Generate Wayfinder types after route changes
- Import: `import { show } from '@/actions/ControllerName'`
- Or: `import { show } from '@/routes/routeName'`

### React Component Structure

- Location: `resources/js/Pages` or `resources/js/components`
- Props: TypeScript interfaces
- Imports: Named imports for tree-shaking
- Styling: Tailwind CSS classes
- Forms: Use `<Form>` component with Wayfinder

### Testing Best Practices

- Test happy paths, failure paths, and edge cases
- Use datasets for repeated test data
- Mock external services
- Use `RefreshDatabase` for feature tests
- Run: `php artisan test --filter=relatedTest`

### Error Handling

- Use exceptions for error states
- Custom exceptions in `app/Exceptions/`
- Render exceptions in `app/Exceptions/Handler.php`
